Transform: S3Objects

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED

  Object1:
    Type: AWS::S3::Object
    DependsOn: Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Properties:
      Target:
        Bucket: !Ref Bucket
        Key: README.md
        ContentType: text/markdown
      Body: |
        # My text file

        This is my text file;
        there are many like it,
        but this one is mine.

  Object2:
    Type: AWS::S3::Object
    DependsOn: Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Properties:
      Target:
        Bucket: !Ref Bucket
        Key: 1-pixel.gif
        ContentType: image/png
      Base64Body: R0lGODdhAQABAIABAP///0qIbCwAAAAAAQABAAACAkQBADs=

  Object3:
    Type: AWS::S3::Object
    DependsOn: Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Properties:
      Source:
        Bucket: !GetAtt Object1.Bucket
        Key: !GetAtt Object1.Key
      Target:
        Bucket: !Ref Bucket
        Key: README-copy.md

  Object4:
    Type: AWS::S3::Object
    DependsOn: Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Properties:
      Target:
        Bucket: !Ref Bucket
        Key: readme.md
      URL: https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-templates/main/README.md
