AWSTemplateFormatVersion: "2010-09-09"

Description: tests DatetimeNow macro

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: Suppressing typical rules for sample purposes only
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_REPLICATION_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
          - S3_BUCKET_DEFAULT_LOCK_ENABLED
          - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Properties:
      Tags:
        - Key: DatetimeNow
          Value:
            Fn::Transform:
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'
